"""update administrators table

Revision ID: 2eff27171002
Revises: 271e5af1fbe4
Create Date: 2025-03-14 15:35:15.632671

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "2eff27171002"
down_revision: Union[str, None] = "271e5af1fbe4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "administrators",
        sa.Column(
            "password", sqlmodel.sql.sqltypes.AutoString(length=2056), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("administrators", "password")
    # ### end Alembic commands ###
