"""change value column in products table

Revision ID: 3bc814e486fe
Revises: 41c97b75a174
Create Date: 2025-03-02 14:47:47.778074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3bc814e486fe'
down_revision: Union[str, None] = '41c97b75a174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('value', sa.Numeric(precision=7, scale=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'value')
    # ### end Alembic commands ###
