"""change products table

Revision ID: 41c97b75a174
Revises: c6229e6df56f
Create Date: 2025-02-27 12:34:05.126407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '41c97b75a174'
down_revision: Union[str, None] = 'c6229e6df56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'retail_price',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'retail_price',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
