"""init

Revision ID: 6c2bec547170
Revises: 4cf05c781d42
Create Date: 2025-02-26 17:07:33.714619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6c2bec547170'
down_revision: Union[str, None] = '4cf05c781d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_unit_id_fkey', 'products', type_='foreignkey')
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'products', 'units', ['unit_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_category_id_fkey', 'products', 'categories', ['category_id'], ['id'])
    op.create_foreign_key('products_unit_id_fkey', 'products', 'units', ['unit_id'], ['id'])
    # ### end Alembic commands ###
