"""update administrators table

Revision ID: 73f21e891c69
Revises: 2eff27171002
Create Date: 2025-03-18 12:32:45.558583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '73f21e891c69'
down_revision: Union[str, None] = '2eff27171002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrators', sa.Column('login', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('administrators', 'login')
    # ### end Alembic commands ###
