"""create supplies and suppliers tables

Revision ID: d21dc0852fe1
Revises: 3bc814e486fe
Create Date: 2025-03-02 15:27:15.477390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21dc0852fe1'
down_revision: Union[str, None] = '3bc814e486fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
