"""create administrators account

Revision ID: eb57b8657e0d
Revises: c74635cc1194
Create Date: 2025-03-14 15:23:42.896784

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "eb57b8657e0d"
down_revision: Union[str, None] = "c74635cc1194"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
